### ISSUE TITLE
Create a readme file on the chat bot

### ISSUE THREAD

**Issue by HidemichiShimura** [HidemichiShimura/slack-cocktail-bot#32]
## GOAL

- To introduce the project
- To illustrate how to start the app in someone's local
- ~~To use the project to show my skills to interview~~
- To show my tech skills to interviewers 
- To make it easier to explain issues from this project and how I solved them to interviewers

## TASK SIZE

1 day

## STEPS

- Create a readme file for the chat bot

## REQUIREMENTS

- Understanding what needs to be in a readme file

## DEPENDENCY

- Predecessor: Extract necessary information for readme from the 3 readme examples
- Successor: -

**Comment by ghost** [comment]
I assume this is a Slack bot for cocktail recipies?

**Comment by HidemichiShimura** [comment]
@shawnjb 
This Slack bot suggests a random cocktail, not recipes.
I might add another feature such as provide cocktail recipes, description of cocktails and so on!
